language: node_js
node_js:
  - stable

cache: npm

env:
  - TERRAFORM_VERSION=0.14.9

before_install:
  - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
  - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TERRAFORM_VERSION"_linux_amd64.zip

script:
  - npm run build || travis_terminate 1
  - ./infrastructure/kitchenator/apply.sh || travis_terminate 1
