language: node_js
node_js:
  - stable

cache: npm

before_install:
  - wget https://releases.hashicorp.com/terraform/0.14.9/terraform_0.14.9_linux_amd64.zip
  - unzip terraform_0.14.9_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_0.14.9_linux_amd64.zip

script:
  - npm run build || travis_terminate 1
  - ./infrastructure/kitchenator/apply.sh || travis_terminate 1
