on:
  push:

jobs:
  zap-full-scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP Full Scan
    steps:
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: 'http://devicenator.com/'
